### PR TITLE
feature/services_extended_request_parameters_pr_dev

### PR DESCRIPTION
**Pull request by quiekedei**
As requested we re-issued [this pull request](https://github.com/QuickBlox/q-municate-services-ios/pull/257) on `development` branch.

### CODE REVIEW

**Comment by object2dot0** [comment]
When is this request going to be merged. We need this feature!

**Comment by Raikerian** [comment]
@object2dot0 this is already available in our development branch here https://github.com/QuickBlox/q-municate-services-ios/tree/development

Use it for pods, or, if you have your own fork, merge [this commit](https://github.com/QuickBlox/q-municate-services-ios/commit/29f21371abf74a12b1bbcf54b6adde5101318e82) into it.

As for release, we are currently in a testing state.

**Comment by object2dot0** [comment]
@Raikerian Thanks for the quick feedback. Usually how much time these things takes to be available on master?

**Comment by Raikerian** [comment]
Appropriate methods were added in 0.4.5. Thank you for your contribution.

**Pull request closed without merging**
